import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Add Task: Work Manager',
  description: 'Generated by create next app'
};

export default function AddTask() {
  return (
    <>
      <div>add task</div>
    </>
  );
}
