import type { Metadata } from 'next';
import AddTask from './AddTask';

export const metadata: Metadata = {
  title: 'Add Task: Work Manager',
  description: 'Generated by create next app'
};

export default function Addtask() {
  return <AddTask />;
}
