import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Login: Work Manager',
  description: 'Generated by create next app'
};

export default function Login() {
  return (
    <>
      <div>Login</div>
    </>
  );
}
