import type { Metadata } from 'next';
import LogIn from './Login';
export const metadata: Metadata = {
  title: 'Login: Work Manager',
  description: 'Generated by create next app'
};

export default function Login() {
  return <LogIn />;
}
