import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Show-Task: Work Manager',
  description: 'Generated by create next app'
};

export default function ShowTask() {
  return (
    <>
      <div>Show Task</div>
    </>
  );
}
