import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Signup: Work Manager',
  description: 'Generated by create next app'
};

export default function Signup() {
    return (
      <>
        <div>Signup</div>
      </>
    );
  }