import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Info: Work Manager',
  description: 'Generated by create next app'
};

export default function Info() {
  return (
    <>
      <div>this Info</div>
    </>
  );
}
