import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'About: Work Manager',
  description: 'Generated by create next app'
};

export default function About() {
  return (
    <>
      <div>About</div>
    </>
  );
}
